### ISSUE TITLE
Not working with Stimulus 3.0

### ISSUE THREAD

**Issue by xhafan** [stimulus-components/stimulus-password-visibility#4]
I installed this via command `npm install stimulus-password-visibility -D`, and the rest of the installation following the steps on https://stimulus-components.netlify.app/docs/stimulus-password-visibility/. I get this typesctipt compilation error in webpack:

```
      TS2345: Argument of type 'typeof t' is not assignable to parameter of type 'Constructor<Controller>'.
  Types of construct signatures are incompatible.
    Type 'new (context: Context) => t' is not assignable to type 'new (...args: any[]) => Controller'.
      Property 'dispatch' is missing in type 't' but required in type 'Controller'.
```
for line `application.register("password-visibility", PasswordVisibility);`

Not sure if this is caused by me using Stimulus 3.0 instead of Stimulus 2.0...

**Comment by guillaumebriday** [comment]
Stimulus 3 support has been released in https://github.com/stimulus-components/stimulus-password-visibility/releases/tag/v2.0.0 

Does this work for you?
